targets:
  $default:
    builders:
      flutter_gen_runner:
        options: 
          output: lib/app/generated/
          line_length: 80 
          integrations:
            image: true
            flutter_svg: true